name: Publish to Ubuntu PPA

on:
  push:
    tags:
      - 'main'

jobs:
  publish-ppa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Generate Debian Source Package
        run: cargo deb --src

      - name: Upload to Launchpad PPA
        uses: yuezk/publish-ppa-package@v2
        with:
          # Targets your main Launchpad archive drawer
          repository: "ani-4nirudh/ppa" 
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          tarball: "target/debian/*.changes"
          deb_email: "anirudh.sai8296@gmail.com"
          deb_fullname: "Anirudh Singh"
          series: "noble jammy"
